# -*- coding: utf-8 -*-
"""SummarizeCovidLiteratureAbstracts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LiFz2oxom278J2nNUJvkaXRGbih_leaX

This app will summarize the covid literarure abstracts

Install required libraries
"""

#Uncomment for local code
# !pip install -q gradio
# !pip install -q transformers
# !pip install -q sentencepiece
# !pip install -q bert-extractive-summarizer 
# !pip install -q parrot

"""Import required libraries"""

import gradio as gr
import transformers
import sentencepiece
from transformers import pipeline

"""Following section is for checking performance and working of different models for summarization.
Comment the code in productio
"""

#Testing code starts
abstract ='''
The COVID-19 pandemic has urged for the repurposing of existing drugs for rapid management and treatment.
 Renin inhibitors down regulation of ACE2, which is an essential receptor for SARS-CoV-2 infection that is responsible for COVID-19,
  in addition to their ability to act as protease inhibitors were encouraging aspects for their investigation as possible inhibitors 
  of main protease of SARS-CoV-2 via computational studies. A Pharmacophore model was generated using the newly 
  released SARS-COV-2 main protease inhibitors. Virtual screening was performed on renin inhibitors,
   and Drug likeness filter identified remikiren and 0IU as hits. Molecular docking for both compounds
    showed that the orally active renin inhibitor remikiren (Ro 42–5892) of Hoffmann–La Roche exhibited
     good molecular interaction with Cys145 and His41 in the catalytic site of SARS-CoV-2 main protease.
      Molecular dynamics simulation suggested that the drug is stable in the active site of the enzyme.
'''



"""Create a function to generate summary of the abstract provided. The function would accept input text , pretrained model name as parameters"""